-- ============================================================================
-- Sakhi AI — Guardian invite system
-- ----------------------------------------------------------------------------
-- Adds what the two-app architecture needs to link a user with a guardian:
--
--   * guardian_links.relationship   — how the user is related to the guardian
--                                     (Mother, Father, Brother, Sister, Friend,
--                                     Spouse, Guardian, …).
--   * guardian_links.guardian_name / user_name — denormalized display names.
--     Needed because RLS prevents either side from reading the OTHER profile
--     row before a link is accepted, so pending-request cards can still show
--     the other person's name.
--   * profiles.invite_code          — unique 8-char code the USER shares; the
--                                     guardian enters it to request a link.
--   * find_user_by_invite_code()    — security-definer RPC so a guardian can
--                                     resolve a code to a user id + name
--                                     WITHOUT being able to enumerate profiles
--                                     (only matches role='user', never self).
--   * guardian_links delete policy  — either party can remove a link (user
--                                     rejects a request / guardian unlinks).
--
-- Run this in the Supabase SQL Editor after the earlier migrations.
-- ============================================================================

-- ── guardian_links: relationship + denormalized names ────────────────────────
alter table public.guardian_links
  add column if not exists relationship  text,
  add column if not exists guardian_name text,
  add column if not exists user_name     text;

comment on column public.guardian_links.relationship is
  'How the linked user relates to the guardian (Mother, Father, …).';

-- ── profiles: unique invite code ─────────────────────────────────────────────
-- 8 chars from an unambiguous alphabet (no 0/O/1/I). Generated by the client
-- and saved to the user's own row (own-row update policy already exists);
-- existing rows without a code get one on first visit to Guardian Management.
alter table public.profiles add column if not exists invite_code text;

create unique index if not exists profiles_invite_code_key
  on public.profiles (invite_code)
  where invite_code is not null;

comment on column public.profiles.invite_code is
  'Public invite code a guardian enters to request a link. Random 8 chars.';

-- ── Look up a user by invite code (guardian side) ────────────────────────────
-- SECURITY DEFINER: runs as the table owner so the guardian can resolve a code
-- without a select policy on profiles — it returns ONLY the user id + name for
-- an exact code match on a role='user' account, and never the caller themself.
create or replace function public.find_user_by_invite_code(code text)
returns table (user_id uuid, full_name text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
    select p.id, p.full_name
    from public.profiles p
    where p.invite_code = upper(btrim(code))
      and p.role = 'user'
      and p.id <> auth.uid()
    limit 1;
end;
$$;

revoke execute on function public.find_user_by_invite_code(text) from public, anon;
grant execute on function public.find_user_by_invite_code(text) to authenticated;

-- ── Either party can remove a link ───────────────────────────────────────────
-- User rejects a pending request (delete instead of a 'rejected' status, which
-- the status check constraint does not allow) or guardian unlinks a member.
drop policy if exists "guardian_links_delete_own" on public.guardian_links;
create policy "guardian_links_delete_own"
  on public.guardian_links
  for delete
  using (guardian_id = auth.uid() or user_id = auth.uid());
